In [1]:
# Imports
import numpy as np
import pandas as pd

In [2]:
# Read in US Foreign Aid dataset
df = pd.read_csv('us_foreign_aid_complete.csv')

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (42) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986235 entries, 0 to 986234
Data columns (total 48 columns):
country_id                     986235 non-null int64
country_code                   985949 non-null object
country_name                   986235 non-null object
region_id                      986235 non-null int64
region_name                    986235 non-null object
income_group_id                791788 non-null float64
income_group_name              791788 non-null object
income_group_acronym           791788 non-null object
implementing_agency_id         986235 non-null int64
implementing_agency_acronym    985536 non-null object
implementing_agency_name       986235 non-null object
implementing_subagency_id      986235 non-null int64
subagency_acronym              888366 non-null object
subagency_name                 986235 non-null object
channel_category_id            986235 non-null int64
channel_category_name          986235 non-null object
channel_subcategory_id         986235 non-null int64
channel_subcategory_name       986235 non-null object
channel_id                     986235 non-null int64
channel_name                   986235 non-null object
dac_category_id                986235 non-null int64
dac_category_name              986235 non-null object
dac_sector_code                986235 non-null int64
dac_sector_name                986235 non-null object
dac_purpose_code               986235 non-null int64
dac_purpose_name               986235 non-null object
funding_account_id             986235 non-null object
funding_account_name           986235 non-null object
funding_agency_id              986235 non-null int64
funding_agency_name            986235 non-null object
funding_agency_acronym         985328 non-null object
assistance_category_id         986235 non-null int64
assistance_category_name       986235 non-null object
aid_type_group_id              986235 non-null int64
aid_type_group_name            986235 non-null object
activity_id                    986235 non-null int64
activity_name                  986069 non-null object
activity_project_number        770306 non-null object
activity_start_date            223044 non-null object
activity_end_date              220162 non-null object
transaction_type_id            986235 non-null int64
transaction_type_name          986235 non-null object
fiscal_year                    986235 non-null object
current_amount                 986235 non-null int64
constant_amount                986235 non-null int64
USG_sector_id                  986235 non-null int64
USG_sector_name                986235 non-null object
submission_id                  986235 non-null int64
dtypes: float64(1), int64(19), object(28)
memory usage: 361.2+ MB

In [3]:
df.head()

,country_id,country_code,country_name,region_id,region_name,income_group_id,income_group_name,income_group_acronym,implementing_agency_id,implementing_agency_acronym,...,activity_start_date,activity_end_date,transaction_type_id,transaction_type_name,fiscal_year,current_amount,constant_amount,USG_sector_id,USG_sector_name,submission_id
0,4,AFG,Afghanistan,4,South and Central Asia,1.0,Low Income Country,LIC,7,DOD,...,NaN,NaN,2,Obligations,2011,9941000000,10914528417,3,Stabilization Operations and Security Sector R...,28
1,4,AFG,Afghanistan,4,South and Central Asia,1.0,Low Income Country,LIC,7,DOD,...,NaN,NaN,2,Obligations,2012,9243000000,9966142830,3,Stabilization Operations and Security Sector R...,28
2,4,AFG,Afghanistan,4,South and Central Asia,1.0,Low Income Country,LIC,7,DOD,...,NaN,NaN,3,Disbursements,2011,7840175215,8607968532,3,Stabilization Operations and Security Sector R...,28
3,4,AFG,Afghanistan,4,South and Central Asia,1.0,Low Income Country,LIC,7,DOD,...,NaN,NaN,3,Disbursements,2013,7764310985,8232733951,3,Stabilization Operations and Security Sector R...,28
4,4,AFG,Afghanistan,4,South and Central Asia,1.0,Low Income Country,LIC,7,DOD,...,NaN,NaN,2,Obligations,2013,6928000000,7345968099,3,Stabilization Operations and Security Sector R...,28

In [4]:
df.fiscal_year.unique()

array(['2011', '2012', '2013', '2015', '2010', '2008', '2009', '2006',
       '2014', '2017', '2007', '2003', '2016', '1947', '1973', '2000',
       '1979', '1972', '1995', '2005', '2004', '1996', '2002', '1993',
       '2001', '1985', '1994', '1986', '1999', '1991', '1971', '1988',
       '1998', '1992', '1997', '1987', '1989', '1990', '1974', '1970',
       '1952', '2018', '1949', '1984', '1969', '1951', '1982', '1983',
       '1980', '1981', '1978', '1968', '1950', '1976', '2019', '1977',
       '1954', '1946', '1967', '1966', '1975', '1976tq', '1962', '1956',
       '1953', '1948', '1963', '1959', '1957', '1965', '1955', '1964',
       '1960', '1961', '1958', 2012, 2011, 2002, 2009, 2007, 2001, 2010,
       2008, 2018, 2003, 2004, 2014, 2006, 2016, 2017, 2005, 2015, 2013,
       2019, 2000, 1999, 1990, 1998, 1997, 1996, 1959, 1992, 1993, 1969,
       1995, 1966, 1967, 1991, 1989, 1994, 1973, 1974, 1988, 1955, 1977,
       1979, 1970, 1975, 1978, 1987, 1982, 1951, 1976, 1965, 1962, 1984,
       1954, 1986, 1956, 1950, 1980, 1968, 1983, 1963, 1985, 1957, 1972,
       1961, 1960, 1981, 1964, 1958, 1971, 1952, 1953], dtype=object)